/*
 * canal_messages.h
 * DCU
 *
 *  WARNING: DO NOT EDIT. THIS WAS AN AUTOGENERATED FILE.
 *
 *  Created on: 2023/10/3
 *     Authors: Samuel Parent, Dharak Verma
 *
 *                    ..::^~~~!!~~~^^:..
 *                .:^!7??JJJJJJJJJJJJ??7!~:.
 *              :~7?JJJ???????????????JJJJ??!^.
 *           .^7?JJJ???JJJJJJ??????????????JJJ?~:
 *          ^7JJ???????777777???JJJJJJJ???????JJ?~.
 *        .!JJ???????????7!~^::::^~!!7??JJ???????J7:
 *       :7JJJ??????????JJJJ??7~:    ..:~7?J??????J?^
 *      .7J???????????????????JJ?!.       :7J??????J?^
 *     .~J??????????????????JJJJ?!.       .7J???????J7.
 *     :?J?????????????JJJJ??7!^.      .:~???????????J~
 *     ^???????????JJJ??7~^:..      .:~7?JJ??????????J!.
 *     ^????????JJ?7~^:.        .:~!?JJJ?????????????J!.
 *     ^????????!^.          .:~7?JJJ????????????????J!.
 *     .7J????!.            :7?JJ?????????????????????^
 *      ~JJ?J7.             ~JJJJ???????????????????J!.
 *      .!J???^.            .^!7?JJJJJJ????????????J7:
 *       .!?J??7^.              .:^~!7???JJJJJ????J7:
 *        .^?JJJJ?7~.                 ..:^~~!7????!.
 *          .!?JJJJ?:                         ..::
 *            :~??!:
 *              ..
 */

#ifndef INC_CANAL_DCU_MESSAGES_H_
#define INC_CANAL_DCU_MESSAGES_H_

 /*********************************************************
 *                      INCLUDES
 *********************************************************/
#include <stdio.h>
#include <stdint.h>
#include <string.h>
#include "canal_types.h"

/*********************************************************
*                        ENUMS
*********************************************************/

typedef enum {
    UNKNOWN_CANAL_ID =                  ((uint32_t) 0x000), 
    VEHICLEINFO_CANAL_ID =              ((uint32_t) 0x503), 
    //i.e. instead of correspond to 2, the enum value DASHANSWER will correspond to the integer 0x55 specifically
    DASHBOARDANSWER_CANAL_ID =          ((uint32_t) 0x55),
    DASHBOARDQUESTION_CANAL_ID =        ((uint32_t) 0x54),
} TeMessageID;

/*********************************************************
*                  CAN MESSAGE QUEUES
*********************************************************/

osMessageQueueId_t canVehicleInfoQueue;
TeMessageID canMessageId;

//DashMessage struct definition
typedef struct DashMessage {

    TsVehicleInfo VehicleInfo;
    TsDashboardAnswer DashboardAnswer;
    TsDashboardQuestion DashboardQuestion;
    TeMessageID canMessageId; //will indicate which struct is populated, therefore which struct to read from DashMessage on the receiving end

}S_DashMessage;


/*********************************************************
*                     MESSAGE STRUCTS
*********************************************************/
/** 
 * Message: VehicleInfo
 * Senders: ['FC']
 * Receivers: ['DCU']
 * Cycle Time: Undefined
 * Bus: Undefined
 */
typedef struct VehicleInfo {    
    // Unit: None
    uint8_t MaximumPowerAvailablePercentage;    
    // Unit: %
    uint8_t SocPercentage;    
    // Unit: None
    uint8_t VcuErrors;    
    // Unit: km/h
    uint8_t VehicleSpeed;    
    // Unit: None
    uint8_t VehicleStatus;
}TsVehicleInfo;

/** 
 * Message: DashboardAnswer
 * Senders: ['DCU']
 * Receivers: ['FC']
 * Cycle Time: Undefined
 * Bus: Undefined
 */
typedef struct DashboardAnswer {    
    // Unit: None
    uint8_t DcuAnswer;
}TsDashboardAnswer;

/** 
 * Message: DashboardQuestion
 * Senders: ['FC']
 * Receivers: ['DCU']
 * Cycle Time: Undefined
 * Bus: Undefined
 */
typedef struct DashboardQuestion {    
    // Unit: None
    uint8_t DcuQuestion;
}TsDashboardQuestion;


/*********************************************************
*                       MESSAGE MACROS
*********************************************************/
#define NUM_RX_MESSAGES    (2)
#define NUM_TX_MESSAGES    (1)
#define TOTAL_MESSAGES     (3)

//in bytes
#define VEHICLEINFO_DATA_LENGTH              (5)
#define DASHBOARDANSWER_DATA_LENGTH          (1)
#define DASHBOARDQUESTION_DATA_LENGTH        (1)
/*********************************************************
*                       SIGNAL MACROS
*********************************************************/
// Message: VehicleInfo

// Signal: MaximumPowerAvailablePercentage
#define VEHICLEINFO_MAXIMUMPOWERAVAILABLEPERCENTAGE_START    (0)
#define VEHICLEINFO_MAXIMUMPOWERAVAILABLEPERCENTAGE_LENGTH   (7)
#define VEHICLEINFO_MAXIMUMPOWERAVAILABLEPERCENTAGE_FACTOR   (1)
#define VEHICLEINFO_MAXIMUMPOWERAVAILABLEPERCENTAGE_OFFSET   (0)

// Signal: SocPercentage
#define VEHICLEINFO_SOCPERCENTAGE_START    (8)
#define VEHICLEINFO_SOCPERCENTAGE_LENGTH   (7)
#define VEHICLEINFO_SOCPERCENTAGE_FACTOR   (1)
#define VEHICLEINFO_SOCPERCENTAGE_OFFSET   (0)

// Signal: VcuErrors
#define VEHICLEINFO_VCUERRORS_START    (16)
#define VEHICLEINFO_VCUERRORS_LENGTH   (8)
#define VEHICLEINFO_VCUERRORS_FACTOR   (1)
#define VEHICLEINFO_VCUERRORS_OFFSET   (0)

// Signal: VehicleSpeed
#define VEHICLEINFO_VEHICLESPEED_START    (24)
#define VEHICLEINFO_VEHICLESPEED_LENGTH   (8)
#define VEHICLEINFO_VEHICLESPEED_FACTOR   (1)
#define VEHICLEINFO_VEHICLESPEED_OFFSET   (0)

// Signal: VehicleStatus
#define VEHICLEINFO_VEHICLESTATUS_START    (32)
#define VEHICLEINFO_VEHICLESTATUS_LENGTH   (2)
#define VEHICLEINFO_VEHICLESTATUS_FACTOR   (1)
#define VEHICLEINFO_VEHICLESTATUS_OFFSET   (0)

// Message: DashboardAnswer

// Signal: DcuAnswer
#define DASHBOARDANSWER_DCUANSWER_START    (0)
#define DASHBOARDANSWER_DCUANSWER_LENGTH   (8)
#define DASHBOARDANSWER_DCUANSWER_FACTOR   (1)
#define DASHBOARDANSWER_DCUANSWER_OFFSET   (0)

// Message: DashboardQuestion

// Signal: DcuQuestion
#define DASHBOARDQUESTION_DCUQUESTION_START    (0)
#define DASHBOARDQUESTION_DCUQUESTION_LENGTH   (8)
#define DASHBOARDQUESTION_DCUQUESTION_FACTOR   (1)
#define DASHBOARDQUESTION_DCUQUESTION_OFFSET   (0)


/*********************************************************
*                 GLOBAL STRUCT DECLARATIONS
*********************************************************/
extern volatile TsVehicleInfo              VehicleInfo;
extern volatile TsDashboardAnswer          DashboardAnswer;
extern volatile TsDashboardQuestion        DashboardQuestion;

/*********************************************************
*               PUBLIC FUNCTION DECLARATIONS
*********************************************************/
void Print_VehicleInfo(void);
void Print_DashboardAnswer(void);
void Print_DashboardQuestion(void);

TeCanALRet Print_Message(uint32_t *ID);
TeCanALRet GetTxDataLength(TeMessageID *ID, uint32_t *dlc);
TeCanALRet MarshalBinary(TeMessageID *ID, uint8_t* rawData);
TeCanALRet UnmarshalBinary(uint32_t *ID, uint8_t* txData);

#endif /* INC_CANAL_DCU_MESSAGES_H_ */
